### ISSUE TITLE
Why am I getting mail from Bee Recruiter when I'm using VAYUZ Careers?

### ISSUE THREAD

**Issue by naveesha-vayuz** [milivayuz/VAYUZ_Career#156]
![image](https://github.com/milivayuz/VAYUZ_Career/assets/121479721/9f470706-c579-4690-aaab-110c9924e482)

**Comment by PrakVayuz** [comment]
Fixed

**Comment by milivayuz** [comment]
still getting it from bee recruitor
<img width="181" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/d4cad65c-a320-4648-9496-a11eaa87a515">
